### PR TITLE
Make voting process clearer

### PR DESCRIPTION
**Pull request by BenGitter**
Proposed is the following change to `rule #3`:

> Players cast their votes by reacting with a `+1` or a `-1` to the pull request message.

If official voting can only be done by reacting with a `+1` or `-1` to the pull request message, everyone can directly see the current votes without having to go through all the comments.

### CODE REVIEW

**Comment by JacksonBates** [comment]
Yes, but it would also help me if they included a comment just to say 'voted', since reactions don't trigger notifications.

**Comment by JacksonBates** [comment]
Side note: #3 style numbering in comments links to the PR or Issue with that number :)

**Comment by mohamedeliwa** [comment]
It's better to do Both methods reacting and commenting. not just reacting

**Comment by mohamedeliwa** [comment]
yes

**Comment by JacksonBates** [comment]
@mikagrubinen Thanks for voting.

Technically, since this rule is only a proposal, you may vote for this (or against) in any way that is clear in this comment thread - as you have.

If Ben's proposal passes then the original commit message will be where the votes +1 or -1 will be stored.

As you imply, this might get a bit confusing - but we'll cross that bridge when we come to it.

Welcome to the game :)

**Comment by JacksonBates** [comment]
Current Status: 2 Votes for, 1 Against.

**Comment by camper-fcc** [comment]
Even though I have no objection to the `+1`/`-1` buttons in general, I think this rule will discourage people from reading through the comments in order to understand the reasoning behind people's votes. I think it'll also discourage people from explaining their vote, which might not be helpful to the creator of the pull request. So, I'm voting 'no' on this.

**Comment by ltnKoen** [comment]
I vote for this proposal.

**Comment by JacksonBates** [comment]
Holy moly! A year later we have a deciding vote!

Since there is a merge conflict and I haven't had this repo on my computer for a long time, I'll get around to merging this as soon as I can, but likely a couple of days.

@ltnKoen welcome! You are currently the only active player, but we'll see if you've inspired a reawakening of the democratic spirit of the other players!

**Pull request merged**
