### PR TITLE
stickers rule!

### PR DESCRIPTION
**Pull request by JacksonBates**
## 5 - Stickers
If a rule is accepted,the player that proposed it will be awarded a 3x3cm hexagonal laptop sticker.
The number of stickers will be tracked on the wiki.
(The stickers exist in-game only, unfortunately)

### CODE REVIEW

**Comment by ArielLeslie** [comment]
If someone is artsy, it could "desktop sticker" instead of a "laptop sticker" it could just be an image file that people can add to their desktop background. (The image file could just be in an assets folder.)

**Comment by JacksonBates** [comment]
@camper-fcc At the moment the stickers are completely pointless, essentially they are just an in-game variable incremented by a manual counter. Some Nomic games introduce curriences / goods / titles / resources etc...but in my experience the initial point system that is most likely to attract more devs is STICKERS...even if they are imaginary.

Contributors to the repo (game) will be able to edit the wiki themselves - so initially we can track our own sticker count (and any other variables that are created by future rules).

A future rule might empower one particular player as a record keeper...but all that is to be decided as the game progresses :)

@ArielLeslie if we wanted to, we could can some better representation of the stickers like an image. Given the skillset of our community, someone might even come up with a bot that issues them (something like font-awesome could be an easy source for digital stickers), although how the bot would issue them I don't actually know...just spit-balling :)

**Comment by JacksonBates** [comment]
I also vote for this rule to pass - because there isn't a rule to stop me ;)

It needs one more vote to pass...ahem...@ArielLeslie riel

**Comment by ArielLeslie** [comment]
I was thinking simpler than a bot with just a default PR merge message that says "get yourself a sticker from the assets folder".

**Comment by JacksonBates** [comment]
ooh, can we have default PR merge messages? I was unaware of that. I'm gonna dig around in the settings and see what else I can do...

**Comment by ArielLeslie** [comment]
I know that you can create saved replies, so it's pretty common for maintainers to use those when they merge a PR. 

image

**Comment by JacksonBates** [comment]
Oh cool I'll use that if we end up issuing stickers like you suggested.

Votes for: Camper and Me
Votes against: --
**Abstaining for unspecified reasons:** @ArielLeslie

**Comment by JacksonBates** [comment]
Oh, I just saw the thumbs up on the original PR - Presumably that's a yes vote, @ArielLeslie. My apologies!!!

The Rule passes! 🎆 🎉

**Pull request merged**
