### PR TITLE
Rule 10 - Proposals

### PR DESCRIPTION
**Pull request by ltnKoen**
Add new rule:

## 10 - Proposals
By submitting a Github Pull Request, players may propose any change to this ruleset, including the addition of new rules as well as the amendment or removal of existing rules.
All such proposals are subject to the same rules as new rules proposals. In particular, a proposal must be accepted by vote, as described in rule 3 - Rule Acceptance, before it is passed into effect; and players cannot make a new proposal if there is any outstanding proposals they have not personally cast a vote on, as described in rule 4 - Citizenship Rights.

### CODE REVIEW

**Comment by JacksonBates** [comment]
I think this just clarifies what is already implied, but I agree with the clarification!

I also appreciate the revival of the game. I probably would have voted yes to anything!

**Comment by mohamedeliwa** [comment]
I vote yes too.
 I'm happy this game is revived again. I hope we can improve it so it attracts more players

**Comment by weinerjm14** [comment]
Clarification is always helpful, thank you. Voted yes

**Comment by JacksonBates** [comment]
WooHoo! Nomic is back on and a rule can now be accepted! Thanks @weinerjm14 :tada:

**Pull request merged**
