### PR TITLE
give stickers and titles a purpose

### PR DESCRIPTION
**Pull request by JacksonBates**
## 9 - Squish Bugs
If a player has accumulated bugs in their software, they can pay another player with the title 'Hunter of Bugs' to remove the bug for them at a cost of ONE sticker which will be paid directly to the 'Hunter of Bugs'. A player cannot remove their own bugs, even if they are also a 'Hunter of Bugs'

----
### Note
This rule is designed to give stickers and the status of Hunter of Bugs a purpose. It also indirectly introduces something akin to Capitalism into the game...

### CODE REVIEW

**Comment by BenGitter** [comment]
Say I want to pay you a sticker to remove a bug, how would I communicate that? Should we have one issue where these transactions are discussed?

**Comment by JacksonBates** [comment]
Good question, @BenGitter.

I imagined it as an honest box issue, whereby a player would just edit the wiki to remove their bug and give a sticker to the bug hunter of their choice.

But a 'market place' issue thread could be a good idea.

**Comment by BenGitter** [comment]
I vote for if we use an issue thread.

**Comment by JacksonBates** [comment]
I'll change the PR later

**Comment by JacksonBates** [comment]
@BenGitter marketplace idea added :)

**Comment by mohamedeliwa** [comment]
I like the Idea of of giving stickers and the status of Hunter of Bugs a purpose.
I hope we can make this a game more interesting to play.
and the market place issue is a good start, I vote for it.

**Comment by mikagrubinen** [comment]
I vote for this proposal.

Reasoning. I will probably need it :-)

**Comment by JacksonBates** [comment]
Excellent! 3 votes for - the proposal passes!

**Pull request merged**
