### PR TITLE
Updated rule #5 - Stickers

### PR DESCRIPTION
**Pull request by mikagrubinen**
The idea here is to have sticker on wiki that can be downloaded, so that players awarded with the sticker can download and use it as their profile picture.

### CODE REVIEW

**Comment by JacksonBates** [comment]
@arielLeslie made some similar comments when I initially proposed the sticker rule.

I'm not opposed to the idea, but we'd need to figure out the implementation of the rule better before I'd vote on it.

For example:

Who makes the stickers?
Do you get a different style of sticker every time?
If you give away the sticker to a Hunter of Bugs, do you have to remove it from your profile?

**Comment by mohamedeliwa** [comment]
I vote against .. I like the idea of making a purpose to the game, but this idea "I think" is not a sufficient purpose to motivate us to play. We need a stronger and better idea.

**Comment by camper-fcc** [comment]
I also vote against this as it's currently written. I agree with @JacksonBates that some form of this idea could be fun.

**Comment by mikagrubinen** [comment]
Three votes against. I am closing this PR. Even I am against it :-)
I'll figure something better soon.

**Pull request closed without merging**
